force-app/main/default/objects/AccountContact__c/AccountContact__c.object-meta.xml
<CustomObject>
    <label>AccountContact</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountContacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AccountContacts</relationshipLabel>
    <relationshipName>AccountContacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountContactSelector.cls
public with sharing class AccountContactSelector {

    public List<AccountContact__c> selectByContactIdsAndIsPrimaryOrdered(Set<Id> contactIds, Boolean isPrimary) {
        string q = 'SELECT Id, Contact__c, isPrimary__c FROM AccountContact__c WHERE isPrimary__c =: isPrimary AND Contact__c IN :contactIds ORDER BY CreatedDate';
        return Database.query(q);
    }

    public List<AggregateResult> countByContactIdsAndIsPrimary (Set<Id> contactIds, Boolean isPrimary) {
        string q = 'SELECT COUNT(ID), Contact__c, isPrimary__c FROM AccountContact__c GROUP BY Contact__c, isPrimary__c HAVING COUNT(ID) > 1 AND Contact__c IN :contactIds AND isPrimary__c = :isPrimary';
        return Database.query(q);
    }
}