force-app/main/default/objects/AccountContact__c/AccountContact__c.object-meta.xml
<CustomObject>
    <label>AccountContact</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountContacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountContacts</relationshipLabel>
    <relationshipName>AccountContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AccountContacts</relationshipLabel>
    <relationshipName>AccountContacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static List<Account> generateAccounts(Integer amount) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 1; i <= amount; i++) {
            Account account = new Account();
            account.Name = 'Account' + i;
            accounts.add(account);
        }
        insert accounts;
        return accounts;
    }
    
    public static List<Contact> generateContacts(Integer amount) {
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 1; i <= amount; i++) {
            Contact contact = new Contact();
            contact.LastName = 'Contact' + i;
            contacts.add(contact);
        }
        insert contacts;
        return contacts;
    }
    
    public static List<AccountContact__c> generateAccountContacts(Id accountId, Set<Id> contactIds) {
        List<AccountContact__c> accountContacts = new List<AccountContact__c>();
        for (Id contactId : contactIds) {
            AccountContact__c accountContact = new AccountContact__c();
            accountContact.Account__c = accountId;
            accountContact.Contact__c = contactId;
            accountContacts.add(accountContact);
        }
        insert accountContacts;
        return accountContacts;
    }
}